#!/bin/bash
# WP-to-Directus skill installer
#
# Copies bundled templates and scripts from the skill directory into the
# current project root. Idempotent: skips files that already exist.
#
# Usage (from project root):
#   bash .claude/skills/wp-to-directus/setup.sh
#
# Or:
#   cd /path/to/project && bash /path/to/skill/setup.sh

set -e

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(pwd)"

echo "=============================================="
echo "  WP-to-Directus Skill Setup"
echo "=============================================="
echo "  Skill:   $SKILL_DIR"
echo "  Project: $PROJECT_DIR"
echo ""

copy_if_missing() {
  local src="$1"
  local dst="$2"
  if [ -e "$dst" ]; then
    echo "  ~ Skip (exists): $dst"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "  + Copied: $dst"
  fi
}

copy_dir_if_missing() {
  local src="$1"
  local dst="$2"
  if [ -e "$dst" ]; then
    echo "  ~ Skip (exists): $dst"
  else
    cp -r "$src" "$dst"
    echo "  + Copied dir: $dst"
  fi
}

echo "[1/3] Templates"
copy_if_missing "$SKILL_DIR/templates/docker-compose.yml" "$PROJECT_DIR/docker-compose.yml"
copy_if_missing "$SKILL_DIR/templates/.env.example" "$PROJECT_DIR/.env"

echo ""
echo "[2/3] Scripts"
copy_dir_if_missing "$SKILL_DIR/scripts" "$PROJECT_DIR/scripts"

echo ""
echo "[3/3] State directory"
mkdir -p "$PROJECT_DIR/state"
echo "  + Ensured: $PROJECT_DIR/state"
echo ""
echo "Note: .mcp.json will be generated by the skill during the 'mcp_install' phase."
echo "      Do NOT pre-create it manually."

echo ""
echo "=============================================="
echo "  Setup complete"
echo "=============================================="
echo ""
echo "Next steps:"
echo "  1. Edit .env — set passwords, DIRECTUS_ADMIN_TOKEN, and MIGRATION_MODE (test|external)"
echo "  2. Invoke the skill:  /wp-to-directus   (or type a trigger phrase)"
echo ""
echo "The skill will walk you through: env validation -> MCP install -> restart prompt -> migration."
